### PR TITLE
Updating ISR photon

### PR DESCRIPTION
**Pull request by asogaard**
- Creating common config
- Updating photon section of analysis algorithm
- Adding photon systematics
- Updating systematics tree handling

### CODE REVIEW

**Comment by laserkaplan** [comment]
Hi @asogaard,

Few questions before I accept all of the changes:

1. Did you test the new code with both ISR jet and photon channels to make sure the output is OK?
2. What is the use case of the common DAODtoMT config if you also have the photon config being updated?
3. Does the enum class for the sys types need to add the prefix you defined?  I guess it's not that intrusive of a change, but not really necessary either.

Thanks,
-Laser

**Comment by asogaard** [comment]
Hi @laserkaplan,

1. No, I didn't: I have (tried to) leave the ISR jet code and config untouched, so there _shoudn't_ be any changes in the output there; the ISR photon analysis selection was still based on JETM6, so required 400 GeV pT. This meant that hardly any events passed, meaning that there was no real basis for reasonably comparing outputs. I can try do download a QCD multijet file and compare outputs, if you feel that would be a good sanity check.
2. config_DAODtoMT_common.py is more intended as a set of common _definitions_. With the current setup of having two distinct set of configs, with significant overlap, I fear that we could inadvertently end up using (slightly) different definitions for common algorithms, like the basic event selection and fatjet selection and calibration. A common set of definitions would mean that we're sure that we're comparing apples and apples, and that we wouldn't have to maintain two separate sets. These definitions would then be specialised minimally to the extent necessary in the channel-dependent config file (e.g. lowering fatjet pT cut, and setting the desired channel in the dijetISR algorithm config).
3. No, that was added solely for my own understanding, to get at better idea of the provenance of the different systematics in the output. That whole business can be removed again, either before or after merging.

Cheers,
A.

**Comment by laserkaplan** [comment]
1. Yeah, please just try one small local run to make sure the new common config is OK and that the changes to the cxx code don't cause either channel to crash.
2. I totally didn't realize that the changes you made to the photon config file included you commenting out the old code and now just reference the common config!  I agree, this is much cleaner.
3. No problem.  To be frank, it might be nicer to keep these in, since the systematics names by themselves are somewhat nondescript.  I can adjust my own scripts to account for this.

**Comment by asogaard** [comment]
I ran locally on mc15_13TeV.304708.Sherpa_CT10_Zqq_Pt500_1000.merge.DAOD_EXOT18.e4692_s2726_r7772_r7676_p2905 using the current dijetISR and with the revisions in the pull request. The pT spectrum for fatjets with the nominal systematics is attached. Red is the existing version, blue-dashed is the proposed revision. Previous tests on ISR photon signal samples indicate that the selection there is sound as well.
screen shot 2017-03-13 at 15 47 53

**Comment by laserkaplan** [comment]
Boom, that's all I need to see.
Thanks for all the work!

**Pull request merged**
